services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    command: pnpm dev

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: