import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/providers/redux-provider";
import ToastProvider from "@/providers/toast-provider";
import ThemeProvider from "@/providers/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <ReduxProvider>
            <ToastProvider />
            {children}
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
